# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitReleaser < Formula
  desc ""
  homepage "https://github.com/git-releaser/git-releaser"
  version "0.1.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/git-releaser/git-releaser/releases/download/0.1.3/git-releaser_Darwin_arm64.tar.gz"
      sha256 "6a4e5946f91b395dc3e9059132b69b10d8d894b24f09667e0d34f9097d3b0ebc"

      def install
        bin.install "git-releaser"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/git-releaser/git-releaser/releases/download/0.1.3/git-releaser_Darwin_x86_64.tar.gz"
      sha256 "41e304bc6f7043f4a372ca507858e69bd1320eef5a36bd648c355fa898acad8d"

      def install
        bin.install "git-releaser"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/git-releaser/git-releaser/releases/download/0.1.3/git-releaser_Linux_arm64.tar.gz"
      sha256 "9d579deb95c1668d8c2ed7b8d6bbf537624bc853b1b7ab3220ca5fd0bb814f76"

      def install
        bin.install "git-releaser"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/git-releaser/git-releaser/releases/download/0.1.3/git-releaser_Linux_x86_64.tar.gz"
      sha256 "faeff3aff88f5a3b6058f370ec2a1ecb9f1021a3bdc0388d1a0de9a4f7fd2791"

      def install
        bin.install "git-releaser"
      end
    end
  end
end
