# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitReleaser < Formula
  desc ""
  homepage "https://github.com/git-releaser/git-releaser"
  version "0.1.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/git-releaser/git-releaser/releases/download/v0.1.2/git-releaser_Darwin_x86_64.tar.gz"
      sha256 "8df94b24b95e0c9d3e6206cf971fcba7facfbcbb802da79927b39aed01b19275"

      def install
        bin.install "git-releaser"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/git-releaser/git-releaser/releases/download/v0.1.2/git-releaser_Darwin_arm64.tar.gz"
      sha256 "d656cf4a1652564798eb5b63f2108ac617e7ad95fb75bc9f43590d49ce977b2c"

      def install
        bin.install "git-releaser"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/git-releaser/git-releaser/releases/download/v0.1.2/git-releaser_Linux_arm64.tar.gz"
      sha256 "50eb03b5eb463731d64befd0585707d1d7b802c1d8542f3198056588411c972f"

      def install
        bin.install "git-releaser"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/git-releaser/git-releaser/releases/download/v0.1.2/git-releaser_Linux_x86_64.tar.gz"
      sha256 "ef337517eb5927640db7d3f3d817dc8e3bf8fc95f607c3bf849e52499a8b7ec2"

      def install
        bin.install "git-releaser"
      end
    end
  end
end
